#!/usr/bin/env python3
"""
Convert JHR02 prayer-time CSVs into a C 2D array of minutes-past-midnight,
for embedding directly in the firmware (PrayerTimes). Reads the CSVs from this
folder and writes prayer_times_data.h to the sketch root one level up, where
PrayerTimes.ino includes it from.

Row order matches the CSV column order: imsak, subuh, syuruk, zuhur, asar,
maghrib, isyak (7 columns). Input is the full-year file (JHR02_2026_full.csv,
from the official JAKIM e-Solat export -- see convert_full_year.py). The
generated header records exactly which date each row corresponds to via a
parallel day-of-year array, so the firmware can tell "no data for this day"
apart from a real (possibly all-zero) row instead of assuming a full year is
loaded.
"""
import csv
import datetime
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
COLUMNS = ["imsak", "subuh", "syuruk", "zuhur", "asar", "maghrib", "isyak"]
FULL_YEAR_PATH = os.path.join(SCRIPT_DIR, "JHR02_2026_full.csv")


def hhmm_to_minutes(hhmm: str) -> int:
    h, m = hhmm.split(":")
    return int(h) * 60 + int(m)


def load_csv(path):
    rows = []
    with open(path, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            date = datetime.date.fromisoformat(row["date"])
            minutes = [hhmm_to_minutes(row[c]) for c in COLUMNS]
            rows.append((date, minutes))
    return rows


def load_all_rows():
    # The full-year JAKIM export is the only input. An earlier version fell back
    # to per-month JHR02_2026-MM.csv files, from back when only two months had
    # been captured; those are superseded and gone. Missing input is now a hard
    # error rather than a silently-empty table.
    if not os.path.exists(FULL_YEAR_PATH):
        raise SystemExit(
            f"missing {FULL_YEAR_PATH} -- run convert_full_year.py first "
            "to regenerate it from JHR02_2026_full_raw.txt"
        )
    rows = load_csv(FULL_YEAR_PATH)

    rows.sort(key=lambda r: r[0])

    seen = set()
    for date, _ in rows:
        assert date not in seen, f"duplicate date in source data: {date}"
        seen.add(date)

    return rows


def main():
    rows = load_all_rows()
    n = len(rows)

    coverage_note = (
        f"// {n} days loaded (full year -- every day-of-year 1-{n} is present)."
        if n >= 365 else
        f"// {n} days loaded (partial year -- see PRAYER_DOY[] for which day-of-year\n"
        "// each row maps to; missing days simply aren't present in this table)."
    )

    lines = []
    lines.append("// Auto-generated by prayer_times/csv_to_c_array.py -- do not hand-edit.")
    lines.append("// Prayer times for zone JHR02 (Johor Bahru), in minutes past midnight.")
    lines.append(coverage_note)
    lines.append("// Column order: imsak, subuh, syuruk, zuhur, asar, maghrib, isyak.")
    lines.append("")
    lines.append("#pragma once")
    lines.append("")
    lines.append(f"#define PRAYER_TABLE_ROWS {n}")
    lines.append("#define PRAYER_TABLE_COLS 7")
    lines.append("")
    lines.append("enum PrayerColumn {")
    lines.append("    PRAYER_IMSAK = 0,")
    lines.append("    PRAYER_SUBUH,")
    lines.append("    PRAYER_SYURUK,")
    lines.append("    PRAYER_ZUHUR,")
    lines.append("    PRAYER_ASAR,")
    lines.append("    PRAYER_MAGHRIB,")
    lines.append("    PRAYER_ISYAK,")
    lines.append("};")
    lines.append("")

    # Day-of-year for each row (1-366), so the firmware can map "today" -> row
    # index without assuming every day of the year is present.
    lines.append("// Day-of-year (1-366) that each row of PRAYER_MINUTES corresponds to.")
    lines.append(f"static const int16_t PRAYER_DOY[PRAYER_TABLE_ROWS] = {{")
    doy_vals = [str(date.timetuple().tm_yday) for date, _ in rows]
    for i in range(0, len(doy_vals), 20):
        lines.append("    " + ", ".join(doy_vals[i:i + 20]) + ",")
    lines.append("};")
    lines.append("")

    lines.append("// minutes-past-midnight, [row][column] -- see PrayerColumn / PRAYER_DOY above.")
    lines.append("static const int16_t PRAYER_MINUTES[PRAYER_TABLE_ROWS][PRAYER_TABLE_COLS] = {")
    for date, minutes in rows:
        vals = ", ".join(f"{m:3d}" for m in minutes)
        lines.append(f"    {{ {vals} }}, // {date.isoformat()}")
    lines.append("};")
    lines.append("")

    # Writes straight into the sketch root (the parent dir), which is where the
    # firmware #includes it from -- this folder deliberately keeps no copy of its
    # own, so there's exactly one prayer_times_data.h in the tree and no chance of
    # the sketch and the generator drifting apart.
    out_path = os.path.normpath(os.path.join(SCRIPT_DIR, os.pardir, "prayer_times_data.h"))
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {out_path} ({n} rows, {os.path.getsize(out_path)} bytes)")


if __name__ == "__main__":
    main()
